plugins {
    id 'java-library'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.134'
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
    id "dev.nanite.plugins.insaniam" version "0.2.1-SNAPSHOT"
}

version = mod_version
version = insaniamUtils.createModVersion()
group = mod_group_id

insaniam {
    changelog {
        file = file('CHANGELOG.md')
        version = project.version
    }
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

repositories {
    mavenLocal()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    // This line is optional. Access Transformers are automatically detected
    // accessTransformers.add('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            client()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            programArgument "--width=1920"
            programArgument "--height=1080"
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            clientData()

            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    mavenCentral()
    maven {
        url = "https://libraries.minecraft.net/"
    }
}

dependencies {
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishMods {
    dryRun = providers.environmentVariable("GITHUB_TOKEN").getOrNull() == null

    file = jar.archiveFile
    version = project.version
    changelog = insaniamUtils.createChangelog()
    displayName = "FC Bridge ${project.version}"
    type = STABLE

    github {
        repository = "forgecraft/fc-bridge"
        accessToken = providers.environmentVariable("GITHUB_TOKEN")
        commitish = providers.environmentVariable("GITHUB_SHA").orElse("dryRun")
        tagName = providers.environmentVariable("GITHUB_REF_NAME").orElse("dryRun")
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }

//    repositories {
//        def token = providers.environmentVariable("MAVEN_TOKEN")
//        if (token.isPresent()) {
//            maven {
//                name = "forgecraft"
//                url = uri("https://maven.forgecraft.net/repository/maven-releases/")
//                credentials {
//                    username = "forgecraft-org"
//                    password = token.get()
//                }
//            }
//        }
//    }

    // Deploy to github maven
    repositories {
        def token = providers.environmentVariable("GITHUB_TOKEN")
        if (token.isPresent()) {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/forgecraft/fc-bridge")
                credentials {
                    username = providers.environmentVariable("GITHUB_ACTOR").getOrNull()
                    password = token.get()
                }
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
