org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true

minecraft_version=26.1.2
minecraft_version_range=[26.0,)
neo_version=26.1.2.3-beta
neo_version_range=[26.1.0.0,)
loader_version_range=[4,)

mod_version=26.1.2.3

mod_id=fcbridge
mod_name=FC Bridge
mod_license=MIT
mod_group_id=net.forgecraft.mods
mod_authors=ForgeCraft
mod_description=ForgeCraft Bridge Mod
