org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true

parchment_minecraft_version=1.21.9
parchment_mappings_version=2025.10.05

minecraft_version=26.1-snapshot-1
minecraft_version_range=[26.0,)
neo_version=26.1.0.0-alpha.2+snapshot-1
neo_version_range=[26.1.0.0-alpha.2,)
loader_version_range=[4,)

# This literally pains me.
mod_version=26.1.0.0

mod_id=fcbridge
mod_name=FC Bridge
mod_license=MIT
mod_group_id=net.forgecraft.mods
mod_authors=ForgeCraft
mod_description=ForgeCraft Bridge Mod
